include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.realm.dart,]

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
