name: lorcana_collection
description: Lorcana collection and tracking price app
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^4.2.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.2
  intl: ^0.19.0
  realm: ^2.0.0
  riverpod_annotation: ^2.3.5
  transparent_image: ^2.0.1
  url_launcher: ^6.2.6
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
